[package]
name = "libymfm"
version = "0.1.0"
authors = ["Hiromasa Tanaka <h1romas4@gmail.com>"]
edition = "2018"
build = "build.rs"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/rust/lib.rs"

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2"
console_error_panic_hook = { version = "0.1", optional = true }
wee_alloc = { version = "0.4", optional = true }

[profile.release]
opt-level = "s"
