[package]
name = "libymfm-cli"
version = "0.10.2"
authors = ["Hiromasa Tanaka <h1romas4@gmail.com>"]
description = "libymfm CLI"
edition = "2021"

[dependencies]
libymfm = { path = "../../", default-features = false }
clap = "2"
