[package]
name = "libymfm-cli"
version = "0.1.0"
authors = ["h1romas4 <h1romas4@gmail.com>"]
description = "libymfm CLI"
edition = "2018"

[dependencies]
libymfm = { path = "../../", default-features = false }
clap = "2"
