[package]
name = "libymfm-cli"
version = "0.9.1"
authors = ["Hiromasa Tanaka <h1romas4@gmail.com>"]
description = "libymfm CLI"
edition = "2018"

[dependencies]
libymfm = { path = "../../", default-features = false }
clap = "2"
