[package]
name = "rust-wasm32-wasi"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libymfm = { path = "/home/hiromasa/devel/amd64/libymfm.wasm", default-features = false }
